// web-next/src/app/keys/page.tsx
"use client";

import { useState, useEffect, useRef } from "react";
import { getKeys, saveKeys, testOneKey } from "@/lib/api";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import AppShell from "@/components/app-shell";

const PROVIDERS = [
  { env: "GROQ_API_KEY", name: "Groq", hint: "gsk_...", url: "https://console.groq.com/keys", tier: "30 RPM / 14,400 req/วัน", desc: "เร็วที่สุด — แนะนำ" },
  { env: "GOOGLE_API_KEY", name: "Google Gemini", hint: "AIza...", url: "https://aistudio.google.com/apikey", tier: "15 RPM / 1M tokens/วัน", desc: "Google account สมัครทันที" },
  { env: "OPENROUTER_API_KEY", name: "OpenRouter", hint: "sk-or-...", url: "https://openrouter.ai/settings/keys", tier: "โมเดล :free ฟรีถาวร", desc: "มีโมเดลฟรีเยอะ" },
  { env: "CEREBRAS_API_KEY", name: "Cerebras", hint: "csk-...", url: "https://cloud.cerebras.ai/", tier: "30 RPM", desc: "เร็วมาก" },
  { env: "SAMBANOVA_API_KEY", name: "SambaNova", hint: "...", url: "https://cloud.sambanova.ai/apis", tier: "ไม่จำกัด (rate limit)", desc: "ฟรีไม่จำกัด" },
  { env: "NVIDIA_API_KEY", name: "NVIDIA NIM", hint: "nvapi-...", url: "https://build.nvidia.com", tier: "1,000 req ฟรี", desc: "NVIDIA account" },
  { env: "MISTRAL_API_KEY", name: "Mistral AI", hint: "...", url: "https://console.mistral.ai/api-keys/", tier: "ฟรี", desc: "Mistral models" },
  { env: "TOGETHER_API_KEY", name: "Together AI", hint: "...", url: "https://api.together.ai/settings/api-keys", tier: "$5 ฟรี", desc: "เครดิตฟรี" },
  { env: "DEEPINFRA_API_KEY", name: "DeepInfra", hint: "...", url: "https://deepinfra.com/dash/api_keys", tier: "ฟรี", desc: "หลาย models" },
  { env: "COHERE_API_KEY", name: "Cohere", hint: "...", url: "https://dashboard.cohere.com/api-keys", tier: "Trial ฟรี", desc: "Command-R" },
];

export default function KeysPage() {
  const [keys, setKeys] = useState<Record<string, string>>({});
  const [testResults, setTestResults] = useState<Record<string, { status: string; message?: string; latency_ms?: number }>>({});
  const [saveStatus, setSaveStatus] = useState("");
  const saveTimer = useRef<ReturnType<typeof setTimeout>>(undefined);

  useEffect(() => {
    getKeys().then(d => { if (d) setKeys(d.keys); });
  }, []);

  const onInput = (env: string, val: string) => {
    setKeys(prev => ({ ...prev, [env]: val }));
    clearTimeout(saveTimer.current);
    setSaveStatus("saving");
    saveTimer.current = setTimeout(async () => {
      const clean: Record<string, string> = {};
      for (const [k, v] of Object.entries({ ...keys, [env]: val })) {
        if (v?.trim()) clean[k] = v.trim();
      }
      await saveKeys(clean);
      setSaveStatus("saved");
      setTimeout(() => setSaveStatus(""), 3000);
    }, 1500);
  };

  const doTest = async (env: string) => {
    setTestResults(prev => ({ ...prev, [env]: { status: "testing" } }));
    const clean: Record<string, string> = {};
    for (const [k, v] of Object.entries(keys)) { if (v?.trim()) clean[k] = v.trim(); }
    await saveKeys(clean);
    const r = await testOneKey(env);
    setTestResults(prev => ({ ...prev, [env]: r || { status: "error", message: "เชื่อมต่อไม่ได้" } }));
  };

  const testAll = async () => {
    for (const p of PROVIDERS) {
      if (keys[p.env]?.trim()) await doTest(p.env);
    }
  };

  return (
    <AppShell>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-xl font-bold">🔑 จัดการ API Keys</h2>
          <p className="text-sm mt-1 text-muted-foreground">ใส่ key → auto-save | กดทดสอบเพื่อเช็คว่าใช้ได้จริง</p>
        </div>
        <div className="flex items-center gap-3">
          {saveStatus === "saving" && <span className="text-sm text-[var(--clr-yellow)]">⏳ กำลังบันทึก...</span>}
          {saveStatus === "saved" && <span className="text-sm text-[var(--clr-green)]">✅ บันทึกแล้ว!</span>}
          <Button onClick={testAll}>🧪 ทดสอบทั้งหมด</Button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {PROVIDERS.map(p => {
          const hasKey = !!keys[p.env]?.trim();
          const r = testResults[p.env];
          const isOk = r?.status === "ok";
          const isLimit = r?.status === "rate_limited";
          const isTesting = r?.status === "testing";
          const isFail = !!r && !isOk && !isLimit && !isTesting;

          const borderColor = isOk ? "border-[var(--clr-green)]"
            : isLimit ? "border-[var(--clr-yellow)]"
            : isFail ? "border-[var(--clr-red)]"
            : hasKey ? "border-[var(--clr-accent)]" : "";

          return (
            <Card key={p.env} className={borderColor}>
              <div className={`flex items-center justify-between px-4 py-3 border-b ${
                isOk ? "bg-[var(--clr-green)]/5" : isFail ? "bg-[var(--clr-red)]/5" : "bg-secondary/50"
              }`}>
                <div className="flex items-center gap-2">
                  <span className="text-lg">{isTesting ? "⏳" : isOk ? "✅" : isLimit ? "⚠️" : isFail ? "❌" : hasKey ? "🔑" : "⬜"}</span>
                  <span className="font-bold">{p.name}</span>
                </div>
                <div className="flex items-center gap-2">
                  <Button size="sm" disabled={isTesting || !hasKey} onClick={() => doTest(p.env)} className="text-xs h-7">
                    {isTesting ? "⏳" : "🧪 ทดสอบ"}
                  </Button>
                  <a href={p.url} target="_blank" rel="noreferrer">
                    <Button variant="outline" size="sm" className="text-xs h-7">สมัคร →</Button>
                  </a>
                </div>
              </div>
              <CardContent className="p-4">
                <div className="flex items-center gap-3 mb-2">
                  <Badge variant="secondary" className="text-xs">{p.tier}</Badge>
                  <span className="text-xs text-muted-foreground">{p.desc}</span>
                </div>
                <Input type="text" placeholder={p.hint} value={keys[p.env] || ""}
                  onChange={e => onInput(p.env, e.target.value)}
                  className="font-mono text-sm" />
                {r && (
                  <div className={`mt-3 px-3 py-2 rounded-lg text-sm ${
                    isOk ? "bg-[var(--clr-green)]/10" : isLimit ? "bg-[var(--clr-yellow)]/10" : isTesting ? "bg-[var(--clr-accent)]/10" : "bg-[var(--clr-red)]/10"
                  }`}>
                    {isTesting && <span className="text-[var(--clr-accent)]">⏳ กำลังทดสอบ {p.name}...</span>}
                    {isOk && (
                      <div className="flex items-center justify-between">
                        <span className="font-bold text-[var(--clr-green)]">✅ ผ่าน! ใช้ได้จริง</span>
                        {r.latency_ms && <Badge variant="outline" className="text-[var(--clr-green)] text-xs">{r.latency_ms}ms</Badge>}
                      </div>
                    )}
                    {isLimit && <span className="font-bold text-[var(--clr-yellow)]">⚠️ Key ใช้ได้ แต่ถึง rate limit</span>}
                    {isFail && (
                      <>
                        <span className="font-bold text-[var(--clr-red)]">❌ ไม่ผ่าน</span>
                        <div className="text-xs mt-1 text-muted-foreground">{r.message || "Key ไม่ถูกต้องหรือหมดอายุ"}</div>
                      </>
                    )}
                  </div>
                )}
              </CardContent>
            </Card>
          );
        })}
      </div>
    </AppShell>
  );
}

// web/src/routes/keys/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { getKeys, saveKeys, testOneKey } from '$lib/api';

	const PROVIDERS = [
		{ env: 'GROQ_API_KEY', name: 'Groq', hint: 'gsk_...', url: 'https://console.groq.com/keys', tier: '30 RPM / 14,400 req/วัน', desc: 'เร็วที่สุด — แนะนำ' },
		{ env: 'GOOGLE_API_KEY', name: 'Google Gemini', hint: 'AIza...', url: 'https://aistudio.google.com/apikey', tier: '15 RPM / 1M tokens/วัน', desc: 'Google account สมัครทันที' },
		{ env: 'OPENROUTER_API_KEY', name: 'OpenRouter', hint: 'sk-or-...', url: 'https://openrouter.ai/settings/keys', tier: 'โมเดล :free ฟรีถาวร', desc: 'มีโมเดลฟรีเยอะ' },
		{ env: 'CEREBRAS_API_KEY', name: 'Cerebras', hint: 'csk-...', url: 'https://cloud.cerebras.ai/', tier: '30 RPM', desc: 'เร็วมาก' },
		{ env: 'SAMBANOVA_API_KEY', name: 'SambaNova', hint: '...', url: 'https://cloud.sambanova.ai/apis', tier: 'ไม่จำกัด (rate limit)', desc: 'ฟรีไม่จำกัด' },
		{ env: 'NVIDIA_API_KEY', name: 'NVIDIA NIM', hint: 'nvapi-...', url: 'https://build.nvidia.com', tier: '1,000 req ฟรี', desc: 'NVIDIA account' },
		{ env: 'MISTRAL_API_KEY', name: 'Mistral AI', hint: '...', url: 'https://console.mistral.ai/api-keys/', tier: 'ฟรี', desc: 'Mistral models' },
		{ env: 'TOGETHER_API_KEY', name: 'Together AI', hint: '...', url: 'https://api.together.ai/settings/api-keys', tier: '$5 ฟรี', desc: 'เครดิตฟรี' },
		{ env: 'DEEPINFRA_API_KEY', name: 'DeepInfra', hint: '...', url: 'https://deepinfra.com/dash/api_keys', tier: 'ฟรี', desc: 'หลาย models' },
		{ env: 'COHERE_API_KEY', name: 'Cohere', hint: '...', url: 'https://dashboard.cohere.com/api-keys', tier: 'Trial ฟรี', desc: 'Command-R' },
	];

	let keys = $state<Record<string, string>>({});
	let testResults = $state<Record<string, any>>({});
	let saveStatus = $state('');
	let saveTimer: any = null;

	onMount(async () => {
		const d = await getKeys();
		if (d?.keys) keys = d.keys;
	});

	function onInput(env: string, val: string) {
		keys[env] = val;
		clearTimeout(saveTimer);
		saveStatus = 'saving';
		saveTimer = setTimeout(doSave, 1500);
	}

	async function doSave() {
		const clean: Record<string, string> = {};
		for (const [k, v] of Object.entries(keys)) { if (v?.trim()) clean[k] = v.trim(); }
		await saveKeys(clean);
		saveStatus = 'saved';
		setTimeout(() => saveStatus = '', 3000);
	}

	async function doTest(env: string) {
		testResults = { ...testResults, [env]: { status: 'testing' } };
		await doSave();
		const r = await testOneKey(env);
		testResults = { ...testResults, [env]: r || { status: 'error', message: 'เชื่อมต่อไม่ได้' } };
	}

	async function testAll() {
		for (const p of PROVIDERS) {
			if (keys[p.env]?.trim()) {
				await doTest(p.env);
			}
		}
	}
</script>

<div class="flex items-center justify-between mb-6">
	<div>
		<h2 class="text-xl font-bold">🔑 จัดการ API Keys</h2>
		<p class="text-sm mt-1" style="color: var(--text2);">ใส่ key → auto-save | กดทดสอบเพื่อเช็คว่าใช้ได้จริง</p>
	</div>
	<div class="flex items-center gap-3">
		{#if saveStatus === 'saving'}
			<span class="text-sm" style="color: var(--yellow);">⏳ กำลังบันทึก...</span>
		{:else if saveStatus === 'saved'}
			<span class="text-sm" style="color: var(--green);">✅ บันทึกแล้ว!</span>
		{/if}
		<button onclick={testAll}
			class="px-4 py-2 rounded-lg text-sm font-semibold cursor-pointer text-white"
			style="background: var(--accent);">
			🧪 ทดสอบทั้งหมด
		</button>
	</div>
</div>

<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
	{#each PROVIDERS as p}
		{@const hasKey = !!keys[p.env]?.trim()}
		{@const r = testResults[p.env]}
		{@const tested = !!r}
		{@const isOk = r?.status === 'ok'}
		{@const isLimit = r?.status === 'rate_limited'}
		{@const isTesting = r?.status === 'testing'}
		{@const isFail = tested && !isOk && !isLimit && !isTesting}

		<div class="rounded-xl border overflow-hidden transition-all"
			style="background: var(--bg2); border-color: {isOk ? 'var(--green)' : isLimit ? 'var(--yellow)' : isFail ? 'var(--red)' : hasKey ? 'var(--accent)' : 'var(--border)'};">

			<!-- Header -->
			<div class="flex items-center justify-between px-4 py-3"
				style="background: {isOk ? 'rgba(63,185,80,0.08)' : isLimit ? 'rgba(210,153,34,0.08)' : isFail ? 'rgba(248,81,73,0.08)' : 'var(--bg3)'};">
				<div class="flex items-center gap-2">
					{#if isTesting}
						<span class="text-lg animate-spin">⏳</span>
					{:else if isOk}
						<span class="text-lg">✅</span>
					{:else if isLimit}
						<span class="text-lg">⚠️</span>
					{:else if isFail}
						<span class="text-lg">❌</span>
					{:else if hasKey}
						<span class="text-lg">🔑</span>
					{:else}
						<span class="text-lg">⬜</span>
					{/if}
					<span class="font-bold text-base">{p.name}</span>
				</div>
				<div class="flex items-center gap-2">
					<button onclick={() => doTest(p.env)}
						disabled={isTesting || !hasKey}
						class="px-3 py-1.5 rounded-lg text-xs font-bold cursor-pointer disabled:opacity-40 text-white"
						style="background: var(--accent);">
						{isTesting ? '⏳' : '🧪 ทดสอบ'}
					</button>
					<a href={p.url} target="_blank"
						class="px-3 py-1.5 rounded-lg text-xs font-semibold border"
						style="border-color: var(--border); color: var(--accent); background: var(--bg);">
						สมัคร →
					</a>
				</div>
			</div>

			<!-- Body -->
			<div class="px-4 py-3">
				<div class="flex items-center gap-3 mb-2">
					<span class="text-xs px-2 py-0.5 rounded-full" style="background: var(--bg3); color: var(--text2);">{p.tier}</span>
					<span class="text-xs" style="color: var(--text3);">{p.desc}</span>
				</div>

				<input type="text" placeholder={p.hint}
					value={keys[p.env] || ''}
					oninput={(e) => onInput(p.env, (e.target as HTMLInputElement).value)}
					class="w-full px-3 py-2.5 rounded-lg border font-mono text-sm"
					style="background: var(--bg); border-color: var(--border); color: var(--text);">

				<!-- Test Result -->
				{#if r}
					<div class="mt-3 px-3 py-2 rounded-lg text-sm"
						style="background: {isOk ? 'rgba(63,185,80,0.1)' : isLimit ? 'rgba(210,153,34,0.1)' : isTesting ? 'rgba(88,166,255,0.1)' : 'rgba(248,81,73,0.1)'};">
						{#if isTesting}
							<div class="flex items-center gap-2" style="color: var(--accent);">
								<span class="animate-spin">⏳</span>
								<span>กำลังทดสอบ {p.name}...</span>
							</div>
						{:else if isOk}
							<div class="flex items-center justify-between">
								<span style="color: var(--green);" class="font-bold">✅ ผ่าน! ใช้ได้จริง</span>
								<span class="font-mono text-xs px-2 py-0.5 rounded" style="background: rgba(63,185,80,0.2); color: var(--green);">
									{r.latency_ms || '?'}ms
								</span>
							</div>
							{#if r.message}
								<div class="text-xs mt-1" style="color: var(--text2);">{r.message}</div>
							{/if}
						{:else if isLimit}
							<div style="color: var(--yellow);" class="font-bold">⚠️ Key ใช้ได้ แต่ถึง rate limit</div>
							<div class="text-xs mt-1" style="color: var(--text2);">รอสักครู่แล้วลองใหม่ หรือใช้ provider อื่นก่อน</div>
						{:else}
							<div style="color: var(--red);" class="font-bold">❌ ไม่ผ่าน</div>
							<div class="text-xs mt-1" style="color: var(--text2);">{r.message || 'Key ไม่ถูกต้องหรือหมดอายุ'}</div>
						{/if}
					</div>
				{/if}
			</div>
		</div>
	{/each}
</div>
